MovieApp/config/routes.rb
Rails.application.routes.draw do

  get '/movies' => 'movies#index'
  get '/movies/:id' => 'movies#show', as: :movie
  get "/actors" => "actors#index"
  get "/actors/:id" => "actors#show", as: :actor

end

MovieApp/app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :parts 
  has_many :movies, through: :parts
end

MovieApp/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :parts 
  has_many :actors, through: :parts
end

MovieApp/app/models/part.rb
class Part < ActiveRecord::Base
  belongs_to :movie 
  belongs_to :actor
end

MovieApp/app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end
  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

MovieApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MovieApp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
   def index
    @movies = Movie.all
  end
  def show
    @movie = Movie.find(params[:id])
    @actors = @movie.actors
  end
end

MovieApp/app/helpers/actors_helper.rb
module ActorsHelper
end

MovieApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MovieApp/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieApp/app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">

          <!--
          To do: Loop through movies and display each one with this HTML
          <div class="actor col-xs-2">
            actor image goes here
            <h3> actor name goes here </h3>
            <p> actor bio goes here </p>
          </div>
          -->
          <% @actors.each do |actor| %>
          	<div class="actor w3-col m2">
            <%= image_tag actor.image %>
            <h3> <%= actor.first_name %> </h3>
            <p> <%= actor.last_name %> </p>
         	  <%= link_to "Learn more", actor_path(actor) %>
          </div>
          <% end %>
      </div>
</div>

MovieApp/app/views/actors/show.html.erb
<div class="w3-main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
    <div class="info">
    </div>
    <div class="actor">
      <!-- actor image -->
      <%= image_tag @actor.image %>
      <div class="info">
        <h3 class="actor-name"> <%= @actor.first_name %> <%= @actor.last_name %> </h3>
        <p class="actor-bio"> <%= @actor.bio %> </p>
      </div>
    </div>

    <h2>Movies</h2>
    <!-- Display each movie's info here -->
  <% @movies.each do |movie|%>
  	<div class="w3-quarter w3-container w3-padding-24">
      <%= image_tag movie.image %>
      <h3> <%= movie.title %> </h3>
      <p> <%= movie.release_year %> </p>
      <p><%= movie.plot %></p>
      <%= link_to "Learn more", movie_path(movie) %>
    </div>
  <%end%>
  </div>
</div>

MovieApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MovieApp/app/views/movies/index.html.erb
<!--
    To do: Loop through movies and display each one with this HTML
    <div class="movie">
      movie image goes here
      <h3> movie title goes here </h3>
      <p> movie release year goes here </p>
    </div>
    -->   
<div class="w3-main">
  <div class="w3-container w3-center">
  	
  <h2>Popular Films</h2>
  
  <% @movies.each do |movie|%>
  	<div class="w3-quarter w3-container w3-padding-24">
      <%= image_tag movie.image %>
      <h3> <%= movie.title %> </h3>
      <p> <%= movie.release_year %> </p>
      <p><%= movie.plot %></p>
      <%= link_to "Learn more", movie_path(movie) %>
    </div>
  <%end%>

  </div>
</div>

MovieApp/app/views/movies/show.html.erb
<div class="w3-main movie-show w3-container w3-center">
  <div class="w3-container w3-center">
    <div class="movie">
      <div class="info">
        <%= image_tag @movie.image %>
        <h3 class="movie-title"> <%= @movie.title %> </h3>
        <p class="movie-release-year"> <%= @movie.release_year %> </p>
        <p class="movie-plot"> <%= @movie.plot %> </p>
      </div>
    </div>

    <h2>Cast</h2>
    <% @actors.each do |actor| %>
    <div class="actor w3-col m2">
      <%= image_tag actor.image %>
      <h3 class="actor-name"> <%= actor.first_name %> <%= actor.last_name %> </h3>
      <p class="actor-bio"> <%= actor.bio %> </p>
    </div>
    <% end %>

  </div>
</div>